# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 957e79efd7ca39d245f03d90a092d8d466607c0202be28a0eebe379f6148f8ae068c84648d1e0be5928ddcb32c05e4b3c549ce4a52733c56232840b9dee30d74

test:
  secret_key_base: 9d27153831710b35382b537ccda0e9812e555eb40b57c12baf7ac0f3b585d115a11317fa65a59c9f9083be0b3558aaa71723594aba5513d51ea30b91c12fa279

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
